name: Create Release

on:
  push:
    tags:
      - 'V\d.\d.\d'

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract.outputs.version }}
    steps:
      - name: Extract version
        id: extract
        run: echo "version=${GITHUB_REF#refs/tags/V}" >> $GITHUB_OUTPUT
      - name: Echo version
        run: echo ${{ steps.extract.outputs.version }}

  echo-version-ubuntu:
    needs: extract-version
    runs-on: ubuntu-latest
    steps:
      - name: Use VERSION
        run: echo "The version is ${{ needs.extract-version.outputs.version }}"

  echo-version-windows:
    needs: extract-version
    runs-on: windows-latest
    steps:
      - name: Use VERSION
        run: echo "The version is ${{ needs.extract-version.outputs.version }}"