# This YAML file defines a GitHub Actions workflow that creates a release when a tag matching the pattern 'V\d.\d.\d' is pushed.
name: Create Release
run-name: ${{ github.ref_name}}

on:
  push:
    tags:
      - 'V\d.\d.\d'

jobs:
  # Job to extract the version from the tag
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract.outputs.version }}
    steps:
      - name: Extract version
        id: extract
        run: echo "version=${GITHUB_REF#refs/tags/V}" >> $GITHUB_OUTPUT
      - name: Echo version
        run: echo ${{ steps.extract.outputs.version }}
        
  # Job to echo the version on Ubuntu
  echo-version-ubuntu:
    needs: extract-version
    runs-on: ubuntu-latest
    steps:
      - name: Use VERSION
        run: echo "The version is ${{ needs.extract-version.outputs.version }}"

  # Job to echo the version on Windows
  echo-version-windows:
    needs: extract-version
    runs-on: windows-latest
    steps:
      - name: Use VERSION
        run: echo "The version is ${{ needs.extract-version.outputs.version }}"